name: Build and Push
on:
  push:
    branches:
      - '**'

env:
  SET_REPO: matterlabs

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          failure-threshold: warning
      -
        id: set
        run: |
          # Computed org/repo name, docker- prefix is stripped off
          SET_REPO="${SET_REPO:-${{ github.event.organization.login }}}"
          SET_NAME="${SET_NAME:-$(echo '${{ github.event.repository.name }}' | sed 's/^docker-//')}"
          echo "::set-output name=image::$(echo $SET_REPO/$SET_NAME | tr '[:upper:]' '[:lower:]')"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx
      -
        uses: docker/login-action@v1
        with:
          username: zksyncrobot
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.set.outputs.image }}
          tags: |
            type=ref,event=branch,enable=false
            latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ startsWith(github.ref, 'refs/heads/master') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
